package com.imglmd.physicsexps.presentation.core

import androidx.compose.ui.res.stringResource
import com.imglmd.physicsexps.R
import com.imglmd.physicsexps.core.ui.utils.StringKeyProvider

class ExperimentsStringProvider: StringKeyProvider {
    override fun resolve(key: String): Int? = when (key) {
        "j_k" -> R.string.j_k
        "k" -> R.string.k
        "l_m" -> R.string.l_m
        "pa" -> R.string.pa
        "mol_vol" -> R.string.mol_vol
        "atm_p" -> R.string.atm_p
        "nor_t" -> R.string.nor_t
        "j_mol_k" -> R.string.j_mol_k
        "un_gas" -> R.string.un_gas
        "av_const" -> R.string.av_const
        "mol_1" -> R.string.mol_1
        "mol_ph" -> R.string.mol_ph
        "e" -> R.string.e
        "pi" -> R.string.pi
        "math_c" -> R.string.math_c
        "mev" -> R.string.mev
        "eq_atom" -> R.string.eq_atom
        "u" -> R.string.u
        "speed_s" -> R.string.speed_s
        "speed_g" -> R.string.speed_g
        "speed_w" -> R.string.speed_w
        "speed_0" -> R.string.speed_0
        "speed_20" -> R.string.speed_20
        "human" -> R.string.human
        "coulomb_constant" -> R.string.coulomb_constant
        "neutron_mass" -> R.string.neutron_mass
        "proton_mass" -> R.string.proton_mass
        "n_m_2_c_2" -> R.string.n_m_2_c_2
        "electron_mass" -> R.string.electron_mass
        "el_ch" -> R.string.el_ch
        "mass_earth" -> R.string.mass_earth
        "radius_earth" -> R.string.radius_earth
        "gravitational_constant" -> R.string.gravitational_constant
        "m_3_kg_s_2" -> R.string.m_3_kg_s_2
        "constants" -> R.string.constants
        "gravity" -> R.string.gravity
        "pdf" -> R.string.pdf
        "exp_rep" -> R.string.exp_rep
        "w_l_rec" -> R.string.w_l_rec
        "a" -> R.string.a
        "in_ph" -> R.string.in_ph
        "ang_f" -> R.string.ang_f
        "main" -> com.imglmd.physicsexps.core.ui.R.string.main
        "settings" -> com.imglmd.physicsexps.core.ui.R.string.settings
        "coulombs_law" -> com.imglmd.physicsexps.core.ui.R.string.coulombs_law
        "electricity" -> com.imglmd.physicsexps.core.ui.R.string.electricity
        "coulombs_law_desc" -> R.string.coulombs_law_desc
        "q1_10_9" -> R.string.q1_10_9
        "q2_10_9" -> R.string.q2_10_9
        "col_dist" -> R.string.col_dist
        "dist" -> R.string.dist
        "nano" -> R.string.nano
        "doppler_effect" -> com.imglmd.physicsexps.core.ui.R.string.doppler_effect
        "phonics" -> com.imglmd.physicsexps.core.ui.R.string.phonics
        "doppler_desc" -> R.string.doppler_desc
        "free_fall" -> com.imglmd.physicsexps.core.ui.R.string.free_fall
        "kinematics" -> com.imglmd.physicsexps.core.ui.R.string.kinematics
        "free_fall_desc" -> R.string.free_fall_desc
        "harmonic_vibrations" -> com.imglmd.physicsexps.core.ui.R.string.harmonic_vibrations
        "mechanics" -> com.imglmd.physicsexps.core.ui.R.string.mechanics
        "harmonic_vibrations_desc" -> R.string.harmonic_vibrations_desc
        "joule_lenz" -> com.imglmd.physicsexps.core.ui.R.string.joule_lenz
        "joule_lenz_desc" -> R.string.joule_lenz_desc
        "pendulum_desc" -> R.string.pendulum_desc
        "pendulum" -> com.imglmd.physicsexps.core.ui.R.string.pendulum
        "physical_pendulum_desc" -> R.string.physical_pendulum_desc
        "physical_pendulum" -> com.imglmd.physicsexps.core.ui.R.string.physical_pendulum
        "projectile_motion_desc" -> R.string.projectile_motion_desc
        "projectile_motion" -> com.imglmd.physicsexps.core.ui.R.string.projectile_motion
        "radioactive_decay_desc" -> R.string.radioactive_decay_desc
        "radioactive_decay" -> com.imglmd.physicsexps.core.ui.R.string.radioactive_decay
        "nuclear_physics" -> com.imglmd.physicsexps.core.ui.R.string.nuclear_physics
        "spring_pendulum_desc" -> R.string.spring_pendulum_desc
        "spring_pendulum" -> com.imglmd.physicsexps.core.ui.R.string.spring_pendulum
        "first_charge" -> R.string.first_charge
        "second_charge" -> R.string.second_charge
        "distance" -> R.string.distance
        "electric_force" -> R.string.electric_force
        "field_strength_1" -> R.string.field_strength_1
        "field_strength_2" -> R.string.field_strength_2
        "potential_energy" -> R.string.potential_energy
        "nC" -> R.string.nC
        "nN" -> R.string.nN
        "v_m" -> R.string.v_m
        "m" -> R.string.m
        "nJ" -> R.string.nJ
        "solution_idea" -> R.string.solution_idea
        "sol_col_desc" -> R.string.sol_col_desc
        "col_step_1" -> R.string.col_step_1
        "col_step_2" -> R.string.col_step_2
        "col_step_3" -> R.string.col_step_3
        "col_step_4" -> R.string.col_step_4
        "col_step_5" -> R.string.col_step_5
        "col_step_6" -> R.string.col_step_6
        "col_step_7" -> R.string.col_step_7
        "obs_v" -> R.string.obs_v
        "sor_v" -> R.string.sor_v
        "m_s" -> R.string.m_s
        "hz" -> R.string.hz
        "initial_frequency" -> R.string.initial_frequency
        "sv" -> R.string.sv
        "sor_f_apr" -> R.string.sor_f_apr
        "s_f_a" -> R.string.s_f_a
        "dop_sh_apr" -> R.string.dop_sh_apr
        "dop_sh_r" -> R.string.dop_sh_r
        "w_l_apr" -> R.string.w_l_apr
        "dop_step_1" -> R.string.dop_step_1
        "dop_step_2" -> R.string.dop_step_2
        "dop_step_3" -> R.string.dop_step_3
        "dop_step_4" -> R.string.dop_step_4
        "dop_step_5" -> R.string.dop_step_5
        "dop_step_6" -> R.string.dop_step_6
        "dop_step_7" -> R.string.dop_step_7
        "dop_step_8" -> R.string.dop_step_8
        "dop_step_9" -> R.string.dop_step_9
        "body_dur" -> R.string.body_dur
        "s" -> R.string.s
        "time" -> R.string.time
        "v_moment" -> R.string.v_moment
        "dist_tr" -> R.string.dist_tr
        "free_step_1" -> R.string.free_step_1
        "free_step_2" -> R.string.free_step_2
        "free_step_3" -> R.string.free_step_3
        "disp" -> R.string.disp
        "period_o" -> R.string.period_o
        "amp" -> R.string.amp
        "start_c" -> R.string.start_c
        "dur_o" -> R.string.dur_o
        "rad_s" -> R.string.rad_s
        "rad" -> R.string.rad
        "har_step_1" -> R.string.har_step_1
        "har_step_2" -> R.string.har_step_2
        "har_step_3" -> R.string.har_step_3
        "har_step_4" -> R.string.har_step_4
        "har_step_5" -> R.string.har_step_5
        "har_step_6" -> R.string.har_step_6
        "c_f_d" -> R.string.c_f_d
        "amperage" -> R.string.amperage
        "voltage" -> R.string.voltage
        "v" -> R.string.v
        "resistance" -> R.string.resistance
        "ohm" -> R.string.ohm
        "heat_am" -> R.string.heat_am
        "q_h" -> R.string.q_h
        "j" -> R.string.j
        "w" -> R.string.w
        "c" -> R.string.c
        "power" -> R.string.power
        "electric_charge" -> R.string.electric_charge
        "work_e" -> R.string.work_e
        "jou_step_1" -> R.string.jou_step_1
        "jou_step_2" -> R.string.jou_step_2
        "jou_step_3" -> R.string.jou_step_3
        "jou_step_4" -> R.string.jou_step_4
        "jou_step_5" -> R.string.jou_step_5
        "jou_step_6" -> R.string.jou_step_6
        "jou_step_7" -> R.string.jou_step_7
        "jou_step_8" -> R.string.jou_step_8
        "jou_step_9" -> R.string.jou_step_9
        "jou_step_10" -> R.string.jou_step_10
        "jou_step_11" -> R.string.jou_step_11
        "thread" -> R.string.thread
        "period_s" -> R.string.period_s
        "thread_length" -> R.string.thread_length
        "per_o" -> R.string.per_o
        "a_gr" -> R.string.a_gr
        "m_s_2" -> R.string.m_s_2
        "def_ang" -> R.string.def_ang
        "acceleration" -> R.string.acceleration
        "osc_fr" -> R.string.osc_fr
        "max_speed" -> R.string.max_speed
        "max_height" -> R.string.max_height
        "math_step_1" -> R.string.math_step_1
        "math_step_2" -> R.string.math_step_2
        "math_step_3" -> R.string.math_step_3
        "math_step_4" -> R.string.math_step_4
        "math_step_5" -> R.string.math_step_5
        "math_step_6" -> R.string.math_step_6
        "math_step_7" -> R.string.math_step_7
        "math_step_8" -> R.string.math_step_8
        "math_step_9" -> R.string.math_step_9
        "math_step_10" -> R.string.math_step_10
        "math_step_11" -> R.string.math_step_11
        "math_step_12" -> R.string.math_step_12
        "math_step_13" -> R.string.math_step_13
        "math_step_14" -> R.string.math_step_14
        "math_step_15" -> R.string.math_step_15
        "math_step_16" -> R.string.math_step_16
        "weight" -> R.string.weight
        "dist_ax" -> R.string.dist_ax
        "kg" -> R.string.kg
        "kg_m_2" -> R.string.kg_m_2
        "dist_axs" -> R.string.dist_axs
        "n_m" -> R.string.n_m
        "linear_frequency" -> R.string.linear_frequency
        "length_simp" -> R.string.length_simp
        "ang_a" -> R.string.ang_a
        "per" -> R.string.per

        "restoring_moment" -> R.string.restoring_moment
        "potential_energy_" -> R.string.potential_energy_
        "max_ang_v" -> R.string.max_ang_v
        "ph_step_1" -> R.string.ph_step_1
        "ph_step_2" -> R.string.ph_step_2
        "ph_step_3" -> R.string.ph_step_3
        "ph_step_4" -> R.string.ph_step_4
        "ph_step_5" -> R.string.ph_step_5
        "ph_step_6" -> R.string.ph_step_6
        "ph_step_7" -> R.string.ph_step_7
        "ph_step_8" -> R.string.ph_step_8
        "ph_step_9" -> R.string.ph_step_9
        "ph_step_10" -> R.string.ph_step_10
        "ph_step_11" -> R.string.ph_step_11
        "ph_step_12" -> R.string.ph_step_12
        "ph_step_13" -> R.string.ph_step_13
        "ph_step_14" -> R.string.ph_step_14
        "ph_step_15" -> R.string.ph_step_15
        "ph_step_16" -> R.string.ph_step_16
        "moment" -> R.string.moment
        "ang" -> R.string.ang
        "x_m" -> R.string.x_m
        "initial_height" -> R.string.initial_height
        "launch_angle" -> R.string.launch_angle
        "y_m" -> R.string.y_m
        "th_r" -> R.string.th_r
        "max_h" -> R.string.max_h
        "f_time" -> R.string.f_time
        "r_time" -> R.string.r_time
        "h_vel" -> R.string.h_vel
        "in_ver_vel" -> R.string.in_ver_vel
        "impact_velocity" -> R.string.impact_velocity
        "impact_angle" -> R.string.impact_angle
        "pr_step_1" -> R.string.pr_step_1
        "pr_step_2" -> R.string.pr_step_2
        "pr_step_3" -> R.string.pr_step_3
        "pr_step_4" -> R.string.pr_step_4
        "pr_step_5" -> R.string.pr_step_5
        "pr_step_6" -> R.string.pr_step_6
        "pr_step_7" -> R.string.pr_step_7
        "pr_step_8" -> R.string.pr_step_8
        "pr_step_9" -> R.string.pr_step_9
        "initial_velocity" -> R.string.initial_velocity
        "half_life" -> R.string.half_life
        "numb" -> R.string.numb
        "in_count" -> R.string.in_count
        "s_1" -> R.string.s_1
        "half_life_" -> R.string.half_life_
        "decay_time" -> R.string.decay_time
        "nmb_rem" -> R.string.nmb_rem
        "rad_const" -> R.string.rad_const
        "av_life" -> R.string.av_life
        "dec_step_1" -> R.string.dec_step_1
        "dec_step_2" -> R.string.dec_step_2
        "dec_step_3" -> R.string.dec_step_3
        "dec_step_4" -> R.string.dec_step_4
        "dec_step_5" -> R.string.dec_step_5
        "dec_step_6" -> R.string.dec_step_6
        "dec_step_7" -> R.string.dec_step_7
        "spring_constant" -> R.string.spring_constant
        "o_freq" -> R.string.o_freq
        "sp_step_1" -> R.string.sp_step_1
        "sp_step_2" -> R.string.sp_step_2
        "sp_step_3" -> R.string.sp_step_3
        "sp_step_4" -> R.string.sp_step_4
        "sp_step_5" -> R.string.sp_step_5
        "sp_step_6" -> R.string.sp_step_6
        "sp_step_7" -> R.string.sp_step_7
        "sp_step_8" -> R.string.sp_step_8
        "sp_step_9" -> R.string.sp_step_9
        else -> null
    }
}